/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author josue
 */
public class JFVentanPrincipal extends javax.swing.JFrame {

    private String puesto;
    public JFVentanPrincipal(String puesto) {
        initComponents();
        this.puesto = puesto.toLowerCase();
        
        switch (this.puesto) {
            case "ventas":
                jm1.setVisible(true);
                jm2.setVisible(true);
                jm3.setVisible(true);
                jm4.setVisible(true);
                jm5.setVisible(true);
                jm6.setVisible(true);
                jm7.setVisible(true);
                break;
            case "contabilidad":
                jm1.setVisible(false);
                jm2.setVisible(false);
                jm3.setVisible(false);
                jm4.setVisible(true);
                jm5.setVisible(true);
                jm6.setVisible(false);
                jm7.setVisible(false);
                break;
            default:
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm1 = new javax.swing.JMenuItem();
        jm2 = new javax.swing.JMenuItem();
        jm3 = new javax.swing.JMenuItem();
        jm4 = new javax.swing.JMenuItem();
        jm5 = new javax.swing.JMenuItem();
        jm6 = new javax.swing.JMenuItem();
        jm7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setBackground(new java.awt.Color(152, 197, 197));
        jButton2.setForeground(new java.awt.Color(152, 197, 197));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpeg"))); // NOI18N

        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 1073, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );

        jMenu1.setText("Gestionar");

        jm1.setText("Venta Accesorios");
        jm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm1ActionPerformed(evt);
            }
        });
        jMenu1.add(jm1);

        jm2.setText("Venta Vehículo");
        jm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm2ActionPerformed(evt);
            }
        });
        jMenu1.add(jm2);

        jm3.setText("Generar Factura");
        jm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm3ActionPerformed(evt);
            }
        });
        jMenu1.add(jm3);

        jm4.setText("Listar Inventario Piezas");
        jm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm4ActionPerformed(evt);
            }
        });
        jMenu1.add(jm4);

        jm5.setText("Listar  Vehículos Vendidos");
        jm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm5ActionPerformed(evt);
            }
        });
        jMenu1.add(jm5);

        jm6.setText("Reservar Producto");
        jm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm6ActionPerformed(evt);
            }
        });
        jMenu1.add(jm6);

        jm7.setText("Registrar Cliente");
        jm7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm7ActionPerformed(evt);
            }
        });
        jMenu1.add(jm7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm1ActionPerformed
        JFVentanaVentaAccesoriosParte jFVentanaVentaAccesoriosParte = new JFVentanaVentaAccesoriosParte();
        jDesktopPane1.add(jFVentanaVentaAccesoriosParte);
        jFVentanaVentaAccesoriosParte.setVisible(true);
    }//GEN-LAST:event_jm1ActionPerformed

    private void jm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm4ActionPerformed
       JIFListarInventarioPiezas jIFListarInventarioPiezas = new JIFListarInventarioPiezas();
       jDesktopPane1.add(jIFListarInventarioPiezas);
       jIFListarInventarioPiezas.setVisible(true);
    }//GEN-LAST:event_jm4ActionPerformed

    private void jm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm2ActionPerformed
        JIFVentaVehiculo jIFVentaVehiculo = new JIFVentaVehiculo();
        jDesktopPane1.add(jIFVentaVehiculo);
        jIFVentaVehiculo.setVisible(true);
    }//GEN-LAST:event_jm2ActionPerformed

    private void jm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm3ActionPerformed
        JIFGenerarFactura jIFGenerarFactura = new JIFGenerarFactura();
        jDesktopPane1.add(jIFGenerarFactura);
        jIFGenerarFactura.setVisible(true);
    }//GEN-LAST:event_jm3ActionPerformed

    private void jm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm5ActionPerformed
        JIFListarVehiculos jIFListarVehiculos = new JIFListarVehiculos();
        jDesktopPane1.add(jIFListarVehiculos);
        jIFListarVehiculos.setVisible(true);
    }//GEN-LAST:event_jm5ActionPerformed

    private void jm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm6ActionPerformed
        JIFReservarProducto jIFReservarProducto = new JIFReservarProducto();
        jDesktopPane1.add(jIFReservarProducto);
        jIFReservarProducto.setVisible(true);
    }//GEN-LAST:event_jm6ActionPerformed

    private void jm7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm7ActionPerformed
       JIFRegistrarCliente jIFRegistrarCliente = new JIFRegistrarCliente();
       jDesktopPane1.add(jIFRegistrarCliente);
       jIFRegistrarCliente.setVisible(true);
    }//GEN-LAST:event_jm7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVentanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVentanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVentanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVentanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVentanPrincipal("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jm1;
    private javax.swing.JMenuItem jm2;
    private javax.swing.JMenuItem jm3;
    private javax.swing.JMenuItem jm4;
    private javax.swing.JMenuItem jm5;
    private javax.swing.JMenuItem jm6;
    private javax.swing.JMenuItem jm7;
    // End of variables declaration//GEN-END:variables
}
