/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

<<<<<<< HEAD
import javax.swing.ImageIcon;
=======
import Domain.UsuarioActivo;
>>>>>>> 323dea9970a22f404142c4563f5eff74da8c50d7

/**
 *
 * @author josue
 */
public class JFVentanPrincipal extends javax.swing.JFrame {

    private String puesto;
    private UsuarioActivo usuarioActivo;

    public JFVentanPrincipal(String puesto, UsuarioActivo usuarioActivo) {
        initComponents();
<<<<<<< HEAD
        this.setIconImage(new ImageIcon(getClass().getResource("/Assets/icon.png")).getImage());
=======
        this.usuarioActivo = usuarioActivo;
>>>>>>> 323dea9970a22f404142c4563f5eff74da8c50d7
        this.puesto = puesto.toLowerCase();
        switch (this.puesto) {
            case "vendedor":
                jm3.setVisible(true);
                jm5.setVisible(true);
                jm6.setVisible(true);
                jm7.setVisible(true);
                jmiVenta.setVisible(true);
                break;
            case "contador":
                jm3.setVisible(false);
                jm5.setVisible(true);
                jm6.setVisible(false);
                jm7.setVisible(false);
                jmiVenta.setVisible(false);
                break;
            case "Gerente de RRHH":
                break;
            default:
                jm3.setVisible(false);
                jm5.setVisible(false);
                jm6.setVisible(false);
                jm7.setVisible(false);
                jmiVenta.setVisible(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiVenta = new javax.swing.JMenuItem();
        jm3 = new javax.swing.JMenuItem();
        jm5 = new javax.swing.JMenuItem();
        jm6 = new javax.swing.JMenuItem();
        jm7 = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(152, 197, 197));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo.jpeg"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(129, 129, 129))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/menu.png"))); // NOI18N
        jMenu1.setText("Gestionar");
        jMenu1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        jmiVenta.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jmiVenta.setText("Visualizar Productos");
        jmiVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVentaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiVenta);

        jm3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jm3.setText("Generar Factura");
        jm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm3ActionPerformed(evt);
            }
        });
        jMenu1.add(jm3);

        jm5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jm5.setText("Listar  Vehículos Vendidos");
        jm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm5ActionPerformed(evt);
            }
        });
        jMenu1.add(jm5);

        jm6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jm6.setText("Generar Pedido");
        jm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm6ActionPerformed(evt);
            }
        });
        jMenu1.add(jm6);

        jm7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jm7.setText("Registrar Cliente");
        jm7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm7ActionPerformed(evt);
            }
        });
        jMenu1.add(jm7);

        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        jMenu1.add(Clientes);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm3ActionPerformed
        JIFGenerarFactura jIFGenerarFactura = new JIFGenerarFactura();
        jDesktopPane1.add(jIFGenerarFactura);
        jIFGenerarFactura.setVisible(true);
    }//GEN-LAST:event_jm3ActionPerformed

    private void jm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm6ActionPerformed
        JIFReservarProducto jIFReservarProducto = new JIFReservarProducto(usuarioActivo);
        jDesktopPane1.add(jIFReservarProducto);
        jIFReservarProducto.setVisible(true);
    }//GEN-LAST:event_jm6ActionPerformed

    private void jm7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm7ActionPerformed
        JIFRegistrarCliente jIFRegistrarCliente = new JIFRegistrarCliente();
        jDesktopPane1.add(jIFRegistrarCliente);
        jIFRegistrarCliente.setVisible(true);
    }//GEN-LAST:event_jm7ActionPerformed

    private void jm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm5ActionPerformed
        JIFListarVehiculosVendidos jIFListarVehiculos = new JIFListarVehiculosVendidos();
        jDesktopPane1.add(jIFListarVehiculos);
        jIFListarVehiculos.setVisible(true);
    }//GEN-LAST:event_jm5ActionPerformed

    private void jmiVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVentaActionPerformed
        // TODO add your handling code here:
        JIFVentaProducto ventaProducto = new JIFVentaProducto();
        jDesktopPane1.add(ventaProducto);
        ventaProducto.setVisible(true);
    }//GEN-LAST:event_jmiVentaActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed

        JIFMostrarCliente mostrarCliente = new JIFMostrarCliente();
        jDesktopPane1.add(mostrarCliente);
        mostrarCliente.setVisible(true);
    }//GEN-LAST:event_ClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jm3;
    private javax.swing.JMenuItem jm5;
    private javax.swing.JMenuItem jm6;
    private javax.swing.JMenuItem jm7;
    private javax.swing.JMenuItem jmiVenta;
    // End of variables declaration//GEN-END:variables
}
