/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Data.AccesorioData;
import Domain.Accesorio;
import Domain.AccesorioAux;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JIFListarInventarioPiezas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFListarInventarioPiezas
     */
    private JTable tablaAccesoriosPartes;
    private DefaultTableModel dftModeloTabla;
    private JScrollPane scrollPane;
    private AccesorioData accesorioData;

    public JIFListarInventarioPiezas() {
        initComponents();
        this.accesorioData = new AccesorioData();
        this.dftModeloTabla = new DefaultTableModel();
        this.tablaAccesoriosPartes = new JTable();
        this.tablaAccesoriosPartes.setModel(this.dftModeloTabla);
        this.scrollPane = new JScrollPane(this.tablaAccesoriosPartes);
        this.scrollPane.setBounds(5, 10, 750, 400);
        this.add(this.scrollPane);
        this.crearTabla();

    }

    private void crearTabla() {
        try {
            this.dftModeloTabla.addColumn("IDProducto");
            this.dftModeloTabla.addColumn("NombreAccesorio");
            this.dftModeloTabla.addColumn("MarcaAccesorio");
            this.dftModeloTabla.addColumn("DescripcionAccesorio");
            this.dftModeloTabla.addColumn("CategoriaAccesorio");
            this.dftModeloTabla.addColumn("Stock");
            this.dftModeloTabla.addColumn("Ubicacion");
            this.dftModeloTabla.addColumn("Disponible");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void cargarDatos() {
        ArrayList<AccesorioAux> accesorios = this.accesorioData.obtenerAccesorios(new Accesorio(null, null, null));
        for (AccesorioAux accesorio : accesorios) {
            Object[] rowData = {
                accesorio.getIdProducto(),
                accesorio.getNombreAccesorio(),
                accesorio.getMarcaAccesorio(),
                accesorio.getDescripcionAccesorio(),
                accesorio.getCategoriaAccesorio(),
                accesorio.getStock(),
                accesorio.getUbicacion(),
                accesorio.isDisponible()
            };
            dftModeloTabla.addRow(rowData);
        }
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
