/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Data.BaseData;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JIFMovimientosInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFResumenVentas
     */
    public JIFMovimientosInventario() {
        initComponents();
        this.agregarDatosATabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setText("Movimientos Inventario");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarDatosATabla() {
        BaseData baseData = new BaseData() {
        };
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String sql = "SELECT * FROM FinanzaVenta.view_MovimientosInventario"; // Consulta SQL para seleccionar datos de la vista

        try ( java.sql.Connection connection = baseData.getSqlConnection();  ResultSet resultSet = connection.createStatement().executeQuery(sql)) {

            // Limpiar la tabla antes de agregar nuevos datos
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"IDMovimiento", "FechaMovimiento", "TipoMovimiento", "CantidadMovida", "Producto", "Almacen", "EmpleadoResponsable"});
            // Iterar sobre los resultados y agregarlos a la tabla
            while (resultSet.next()) {
                int IDMovimiento = resultSet.getInt("IDMovimiento");
                String FechaMovimiento = resultSet.getString("FechaMovimiento");
                String TipoMovimiento = resultSet.getString("TipoMovimiento");
                int CantidadMovida = resultSet.getInt("CantidadMovida");
                String Producto = resultSet.getString("Producto");
                String Almacen = resultSet.getString("Almacen");
                String EmpleadoResponsable = resultSet.getString("EmpleadoResponsable");

                // Agregar los datos a la tabla
                model.addRow(new Object[]{IDMovimiento, FechaMovimiento, TipoMovimiento, CantidadMovida, Producto, Almacen, EmpleadoResponsable});
            }
        } catch (SQLException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
