/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Data.BaseData;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class JIFResumenVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFResumenVentas
     */
    public JIFResumenVentas() {
        initComponents();
        this.agregarDatosATabla();
    }

    private void agregarDatosATabla() {
        BaseData baseData = new BaseData() {
        };
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String sql = "SELECT * FROM FinanzaVenta.view_ResumenVentas"; // Consulta SQL para seleccionar datos de la vista

        try ( java.sql.Connection connection = baseData.getSqlConnection();  ResultSet resultSet = connection.createStatement().executeQuery(sql)) {

            // Limpiar la tabla antes de agregar nuevos datos
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"IDPedido", "FechaPedido", "EstadoPedido", "IDFactura", "FechaFactura", "TotalFactura", "NombreCliente", "CorreoElectronico"});
            // Iterar sobre los resultados y agregarlos a la tabla
            while (resultSet.next()) {
                int IDPedido = resultSet.getInt("IDPedido");
                String FechaPedido = resultSet.getString("FechaPedido");
                String EstadoPedido = resultSet.getString("EstadoPedido");
                int IDFactura = resultSet.getInt("IDFactura");
                String FechaFactura = resultSet.getString("FechaFactura");
                double TotalFactura = resultSet.getDouble("TotalFactura");
                String NombreCliente = resultSet.getString("NombreCliente");
                String CorreoElectronico = resultSet.getString("CorreoElectronico");

                // Agregar los datos a la tabla
                model.addRow(new Object[]{IDPedido, FechaPedido, EstadoPedido, IDFactura, FechaFactura, TotalFactura, NombreCliente, CorreoElectronico});
            }
        } catch (SQLException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Resumen Ventas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
