/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Data.AccesorioData;
import Data.ComponenteData;
import Data.VehiculoData;
import Domain.Accesorio;
import Domain.AccesorioAux;
import Domain.Componente;
import Domain.ComponenteAux;
import Domain.Vehiculo;
import Domain.VehiculoDisponible;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JIFVentaProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFVentaProducto
     */
    private int indiceComboBox;
    private int posX;
    private int posY;
    private int posX1;
    private int posY1;
    private int posX2;
    private int posY2;
    private int posXText1;
    private int posYText1;
    private int posXText2;
    private int posYText2;
    private int posXText3;
    private int posYText3;
    private int contador;
    private JTable tablaAccesoriosPartes;
    private DefaultTableModel dftModeloTabla;
    private JScrollPane scrollPane;
    private ComponenteData componenteData;
    private AccesorioData accesorioData;
    private VehiculoData vehiculoData;

    public JIFVentaProducto() {
        initComponents();
        this.jComboBox2.removeAllItems();
        this.jComboBox2.addItem("Vehiculo");
        this.jComboBox2.addItem("Accesorio");
        this.jComboBox2.addItem("Componente");
        this.jLabel1.setVisible(false);
        this.jLabel2.setVisible(false);
        this.jLabel3.setVisible(false);
        this.jLabel4.setVisible(false);
        this.jLabel5.setVisible(false);
        this.jLabel7.setVisible(false);
        this.jTextField1.setVisible(false);
        this.jTextField2.setVisible(false);
        this.jTextField3.setVisible(false);
        this.jTextField4.setVisible(false);
        this.jTextField5.setVisible(false);
        this.jTextField6.setVisible(false);
        this.jButton1.setVisible(false);
        this.componenteData = new ComponenteData();
        this.accesorioData = new AccesorioData();
        this.vehiculoData = new VehiculoData();
        this.indiceComboBox = 0;
        this.contador = 0;
        this.dftModeloTabla = new DefaultTableModel();
        this.tablaAccesoriosPartes = new JTable();
        this.tablaAccesoriosPartes.setModel(this.dftModeloTabla);
        this.scrollPane = new JScrollPane(this.tablaAccesoriosPartes);
        this.scrollPane.setBounds(3, 260, 750, 200);
        this.add(this.scrollPane);
    }

    private void crearTablaDatos(int indiceCambio) {
        try {
            // Limpiar las columnas existentes en el modelo de la tabla
            if (this.dftModeloTabla != null) {
                this.dftModeloTabla.setColumnCount(0);

                if (indiceCambio == 0) {
                    this.dftModeloTabla.addColumn("IDProducto");
                    this.dftModeloTabla.addColumn("Marca Vehiculo");
                    this.dftModeloTabla.addColumn("Modelo Vehiculo");
                    this.dftModeloTabla.addColumn("Pais Importacion");
                    this.dftModeloTabla.addColumn("Destinado Venta");
                    this.dftModeloTabla.addColumn("Precio");
                    this.dftModeloTabla.addColumn("Cantidad Producto");
                    this.dftModeloTabla.addColumn("Ubicacion");
                } else if (indiceCambio >= 1) {
                    this.dftModeloTabla.addColumn("IDProducto");
                    this.dftModeloTabla.addColumn("Nombre Componente");
                    this.dftModeloTabla.addColumn("Marca Componente");
                    this.dftModeloTabla.addColumn("Descripcion Componente");
                    this.dftModeloTabla.addColumn("Categoria Componente");
                    this.dftModeloTabla.addColumn("Cantidad Producto");
                    this.dftModeloTabla.addColumn("Ubicacion");
                    this.dftModeloTabla.addColumn("Disponible");
                }

            }
            this.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();

        jLabel6.setText("jLabel6");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setMaximizable(true);

        jLabel1.setText("Marca:");

        jLabel2.setText("Modelo:");

        jLabel3.setText("Precio:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Marca:");

        jLabel5.setText("Nombre:");

        jLabel7.setText("Categoria:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String filtro1 = "", filtro2 = "", filtro3 = "";
        if (this.indiceComboBox == 0) {
            filtro1 = this.jTextField1.getText();
            filtro2 = this.jTextField2.getText();
            filtro3 = this.jTextField3.getText();
        } else if(this.indiceComboBox > 0){
            filtro1 = this.jTextField4.getText();
            filtro2 = this.jTextField5.getText();
            filtro3 = this.jTextField6.getText();
        }
        this.obtenerDatosProducto(filtro1, filtro2, filtro3);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        this.indiceComboBox = this.jComboBox2.getSelectedIndex();
        this.tomarPosiciones();
        if (this.indiceComboBox == 0) {
            this.mostrarFiltrosAccesorioComponente(false);
            this.mostrarFiltrosVehiculo(true);
            this.jButton1.setVisible(true);
        } else if (this.indiceComboBox >= 1) {
            this.mostrarFiltrosAccesorioComponente(true);
            this.mostrarFiltrosVehiculo(false);
            this.jButton1.setVisible(true);
        }
        this.crearTablaDatos(this.jComboBox2.getSelectedIndex());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void mostrarFiltrosAccesorioComponente(boolean mostrar) {
        this.jLabel4.setVisible(mostrar);
        this.jLabel5.setVisible(mostrar);
        this.jLabel7.setVisible(mostrar);

        this.jTextField4.setVisible(mostrar);
        this.jTextField4.setPreferredSize(new Dimension(15, 24));

        this.jTextField5.setVisible(mostrar);
        this.jTextField5.setPreferredSize(new Dimension(15, 24));

        this.jTextField6.setVisible(mostrar);
        this.jTextField6.setPreferredSize(new Dimension(15, 24));
        if (mostrar) {
            int espacioY = 10;

            this.jLabel4.setBounds(this.posX, this.posY, this.jLabel4.getWidth(), this.jLabel4.getHeight());
            this.jLabel5.setBounds(this.posX1, this.posY1 + this.jLabel4.getHeight() + espacioY, this.jLabel5.getWidth(), this.jLabel5.getHeight());
            this.jLabel7.setBounds(this.posX2, this.posY2 + this.jLabel5.getHeight() + espacioY, this.jLabel7.getWidth(), this.jLabel7.getHeight());

            this.jTextField4.setBounds(this.posXText1 + 3, this.posYText1, this.jTextField4.getWidth() - 4, this.jTextField4.getHeight());
            this.jTextField5.setBounds(this.posXText2 + 5, this.posYText2 + this.jTextField4.getHeight() - 8 + espacioY, this.jTextField5.getWidth(), this.jTextField5.getHeight());
            this.jTextField6.setBounds(this.posXText3 + 13, this.posYText3 + this.jTextField5.getHeight() - 8 + espacioY, this.jTextField6.getWidth(), this.jTextField6.getHeight());
        }
        this.repaint();
    }

    private void mostrarFiltrosVehiculo(boolean mostrar) {
        this.jLabel1.setVisible(mostrar);
        this.jLabel2.setVisible(mostrar);
        this.jLabel3.setVisible(mostrar);
        this.jTextField1.setVisible(mostrar);
        this.jTextField2.setVisible(mostrar);
        this.jTextField3.setVisible(mostrar);
        this.repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    private void tomarPosiciones() {
        if (this.contador == 0) {
            // Etiquetas
            this.posX = this.jLabel1.getBounds().x;
            this.posY = this.jLabel1.getBounds().y;

            this.posX1 = this.jLabel2.getBounds().x;
            this.posY1 = this.jLabel2.getBounds().y;

            this.posX2 = this.jLabel3.getBounds().x;
            this.posY2 = this.jLabel3.getBounds().y;

            // Campos de texto
            this.posXText1 = this.jTextField1.getBounds().x;
            this.posYText1 = this.jTextField1.getBounds().y;

            this.posXText2 = this.jTextField2.getBounds().x;
            this.posYText2 = this.jTextField2.getBounds().y;

            this.posXText3 = this.jTextField3.getBounds().x;
            this.posYText3 = this.jTextField3.getBounds().y;
        }
        this.contador++;
    }

    private void obtenerDatosProducto(String filtro1, String filtro2, String filtro3) {
        if (this.indiceComboBox >= 0) {
            switch (this.indiceComboBox) {
                case 0 -> {
                    float precio = 0;
                    if (!filtro3.equals("")) {
                         precio = Float.parseFloat(filtro3);
                    }
                    ArrayList<VehiculoDisponible> vehiculoDisponibles = this.vehiculoData.obtenerVehiculos(new Vehiculo(filtro1, filtro2, precio));
                    this.llenarTablaVehiculo(vehiculoDisponibles);
                }
                case 1 -> {
                    ArrayList<AccesorioAux> accesorioAuxs = this.accesorioData.obtenerAccesorios(new Accesorio(filtro1, filtro2, filtro3));
                    this.llenarTablaComponenteAccesorio(accesorioAuxs, null);
                }
                case 2 -> {
                    ArrayList<ComponenteAux> componenteAuxs = this.componenteData.obtenerComponentes(new Componente(filtro1, filtro2, filtro3));
                    this.llenarTablaComponenteAccesorio(null, componenteAuxs);
                }

            }
        }
    }

    private void llenarTablaComponenteAccesorio(ArrayList<AccesorioAux> accesorioAuxs, ArrayList<ComponenteAux> componenteAuxs) {
        // Limpiar la tabla antes de llenar con nuevos datos
        this.dftModeloTabla.setRowCount(0);

        if (accesorioAuxs != null) {
            for (AccesorioAux accesorio : accesorioAuxs) {
                Object[] rowData = {
                    accesorio.getIdProducto(),
                    accesorio.getNombreAccesorio(),
                    accesorio.getMarcaAccesorio(),
                    accesorio.getDescripcionAccesorio(),
                    accesorio.getCategoriaAccesorio(),
                    accesorio.getStock(),
                    accesorio.getUbicacion(),
                    accesorio.isDisponible()
                };
                this.dftModeloTabla.addRow(rowData);
            }
        }

        if (componenteAuxs != null) {
            for (ComponenteAux componente : componenteAuxs) {
                this.dftModeloTabla.addRow(new Object[]{
                    componente.getIdProducto(),
                    componente.getNombreComponente(),
                    componente.getMarcaComponente(),
                    componente.getDescripcionComponente(),
                    componente.getCategoriaComponente(),
                    componente.getCantidadProducto(),
                    componente.getUbicacion(),
                    componente.isDisponible()
                });
            }
        }
    }

    private void llenarTablaVehiculo(ArrayList<VehiculoDisponible> vehiculoDisponibles) {

        this.dftModeloTabla.setRowCount(0);

        for (VehiculoDisponible vehiculo : vehiculoDisponibles) {
            Object[] rowData = {
                vehiculo.getIdProducto(),
                vehiculo.getMarcaVehiculo(),
                vehiculo.getModeloVehiculo(),
                vehiculo.getPaisImportacion(),
                vehiculo.isDestinadoVenta(),
                vehiculo.getPrecio(),
                vehiculo.getCantidadProducto(),
                vehiculo.getUbicacion()
            };
            this.dftModeloTabla.addRow(rowData);
        }
    }

}
