/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Data.AccesorioData;
import Data.ComponenteData;
import Data.VehiculoData;
import Domain.Accesorio;
import Domain.AccesorioAux;
import Domain.Componente;
import Domain.ComponenteAux;
import Domain.Vehiculo;
import Domain.VehiculoDisponible;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JIFVentaProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFVentaProducto
     */
    private int indiceComboBox;
    private final JTable tablaAccesoriosPartes;
    private final DefaultTableModel dftModeloTabla;
    private final JScrollPane scrollPane;
    private final ComponenteData componenteData;
    private final AccesorioData accesorioData;
    private final VehiculoData vehiculoData;

    public JIFVentaProducto() {
        initComponents();
        this.jComboBox2.removeAllItems();
        this.jComboBox2.addItem("Vehiculo");
        this.jComboBox2.addItem("Accesorio");
        this.jComboBox2.addItem("Componente");
        this.jLabel1.setVisible(false);
        this.jLabel2.setVisible(false);
        this.jLabel3.setVisible(false);
        this.jTextField1.setVisible(false);
        this.jTextField2.setVisible(false);
        this.jTextField3.setVisible(false);
        this.jButton1.setVisible(false);
        this.componenteData = new ComponenteData();
        this.accesorioData = new AccesorioData();
        this.vehiculoData = new VehiculoData();
        this.indiceComboBox = 0;
        this.dftModeloTabla = new DefaultTableModel();
        this.tablaAccesoriosPartes = new JTable();
        this.tablaAccesoriosPartes.setModel(this.dftModeloTabla);
        this.scrollPane = new JScrollPane(this.tablaAccesoriosPartes);
        this.scrollPane.setBounds(3, 260, 750, 200);
        this.add(this.scrollPane);
        this.activarFiltros();
        this.crearTablaDatos(this.jComboBox2.getSelectedIndex());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(152, 197, 197));
        setClosable(true);
        setFrameIcon(null);

        jLabel1.setText("Marca:");

        jLabel2.setText("Modelo:");

        jLabel3.setText("Precio:");

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Buscar por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String filtro1 = "", filtro2 = "", filtro3 = "";
        if (this.indiceComboBox == 0) {
            filtro1 = this.jTextField1.getText();
            filtro2 = this.jTextField2.getText();
            filtro3 = this.jTextField3.getText();
        } else if(this.indiceComboBox > 0){
            filtro1 = this.jTextField1.getText();
            filtro2 = this.jTextField2.getText();
            filtro3 = this.jTextField3.getText();
        }
        this.obtenerDatosProducto(filtro1, filtro2, filtro3);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        this.activarFiltros();
        this.crearTablaDatos(this.jComboBox2.getSelectedIndex());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void activarFiltros(){
        this.indiceComboBox = this.jComboBox2.getSelectedIndex();
        if (this.indiceComboBox == 0) {
            this.mostrarFiltrosVehiculo(true);
            this.jButton1.setVisible(true);
        } else if (this.indiceComboBox >= 1) {
            this.mostrarFiltrosAccesorioComponente(true);
            this.jButton1.setVisible(true);
        }
    }
    
    private void mostrarFiltrosAccesorioComponente(boolean mostrar) {
        
        if (mostrar) {
            this.jLabel1.setVisible(mostrar);
            this.jLabel2.setVisible(mostrar);
            this.jLabel3.setVisible(mostrar);
            this.jLabel1.setText("Marca: ");
            this.jLabel2.setText("Nombre: ");
            this.jLabel3.setText("Categoria: ");
            this.jTextField1.setVisible(mostrar);
            this.jTextField2.setVisible(mostrar);
            this.jTextField3.setVisible(mostrar);
        }
        this.repaint();
    }

    private void mostrarFiltrosVehiculo(boolean mostrar) {
        this.jLabel1.setText("Marca: ");
        this.jLabel2.setText("Modelo: ");
        this.jLabel3.setText("Precio: ");
        this.jLabel1.setVisible(mostrar);
        this.jLabel2.setVisible(mostrar);
        this.jLabel3.setVisible(mostrar);
        this.jTextField1.setVisible(mostrar);
        this.jTextField2.setVisible(mostrar);
        this.jTextField3.setVisible(mostrar);
        this.repaint();

    }
    
    private void crearTablaDatos(int indiceCambio) {
        try {
            // Limpiar las columnas existentes en el modelo de la tabla
            if (this.dftModeloTabla != null) {
                this.dftModeloTabla.setColumnCount(0);

                if (indiceCambio == 0) {
                    this.dftModeloTabla.addColumn("IDProducto");
                    this.dftModeloTabla.addColumn("Marca Vehiculo");
                    this.dftModeloTabla.addColumn("Modelo Vehiculo");
                    this.dftModeloTabla.addColumn("Pais Importacion");
                    this.dftModeloTabla.addColumn("Destinado Venta");
                    this.dftModeloTabla.addColumn("Precio");
                    this.dftModeloTabla.addColumn("Cantidad Producto");
                    this.dftModeloTabla.addColumn("Ubicacion");
                } else if (indiceCambio >= 1) {
                    this.dftModeloTabla.addColumn("IDProducto");
                    this.dftModeloTabla.addColumn("Nombre Componente");
                    this.dftModeloTabla.addColumn("Marca Componente");
                    this.dftModeloTabla.addColumn("Descripcion Componente");
                    this.dftModeloTabla.addColumn("Categoria Componente");
                    this.dftModeloTabla.addColumn("Cantidad Producto");
                    this.dftModeloTabla.addColumn("Ubicacion");
                    this.dftModeloTabla.addColumn("Disponible");
                }

            }
            this.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void obtenerDatosProducto(String filtro1, String filtro2, String filtro3) {
        if (this.indiceComboBox >= 0) {
            switch (this.indiceComboBox) {
                case 0 -> {
                    float precio = 0;
                    if (!filtro3.equals("")) {
                         precio = Float.parseFloat(filtro3);
                    }
                    ArrayList<VehiculoDisponible> vehiculoDisponibles = this.vehiculoData.obtenerVehiculos(new Vehiculo(filtro1, filtro2, precio));
                    this.llenarTablaVehiculo(vehiculoDisponibles);
                }
                case 1 -> {
                    ArrayList<AccesorioAux> accesorioAuxs = this.accesorioData.obtenerAccesorios(new Accesorio(filtro1, filtro2, filtro3));
                    this.llenarTablaComponenteAccesorio(accesorioAuxs, null);
                }
                case 2 -> {
                    ArrayList<ComponenteAux> componenteAuxs = this.componenteData.obtenerComponentes(new Componente(filtro1, filtro2, filtro3));
                    this.llenarTablaComponenteAccesorio(null, componenteAuxs);
                }

            }
        }
    }

    private void llenarTablaComponenteAccesorio(ArrayList<AccesorioAux> accesorioAuxs, ArrayList<ComponenteAux> componenteAuxs) {
        // Limpiar la tabla antes de llenar con nuevos datos
        this.dftModeloTabla.setRowCount(0);

        if (accesorioAuxs != null) {
            for (AccesorioAux accesorio : accesorioAuxs) {
                Object[] rowData = {
                    accesorio.getIdProducto(),
                    accesorio.getNombreAccesorio(),
                    accesorio.getMarcaAccesorio(),
                    accesorio.getDescripcionAccesorio(),
                    accesorio.getCategoriaAccesorio(),
                    accesorio.getStock(),
                    accesorio.getUbicacion(),
                    accesorio.isDisponible()
                };
                this.dftModeloTabla.addRow(rowData);
            }
        }

        if (componenteAuxs != null) {
            for (ComponenteAux componente : componenteAuxs) {
                this.dftModeloTabla.addRow(new Object[]{
                    componente.getIdProducto(),
                    componente.getNombreComponente(),
                    componente.getMarcaComponente(),
                    componente.getDescripcionComponente(),
                    componente.getCategoriaComponente(),
                    componente.getCantidadProducto(),
                    componente.getUbicacion(),
                    componente.isDisponible()
                });
            }
        }
    }

    private void llenarTablaVehiculo(ArrayList<VehiculoDisponible> vehiculoDisponibles) {

        this.dftModeloTabla.setRowCount(0);

        for (VehiculoDisponible vehiculo : vehiculoDisponibles) {
            Object[] rowData = {
                vehiculo.getIdProducto(),
                vehiculo.getMarcaVehiculo(),
                vehiculo.getModeloVehiculo(),
                vehiculo.getPaisImportacion(),
                vehiculo.isDestinadoVenta(),
                vehiculo.getPrecio(),
                vehiculo.getCantidadProducto(),
                vehiculo.getUbicacion()
            };
            this.dftModeloTabla.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
